package address.view;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.*;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.util.Duration;
import tray.notification.NotificationType;
import tray.notification.TrayNotification;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import address.AddressApp;
import database.DBConnection;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private TextField tfusername;
	@FXML
	private Button loginButton;
	@FXML
	private Button cancelButton;
	@FXML
	private PasswordField pfpassword;

	// Event Listener on Button[#loginButton].onAction
	@FXML
	public void loginButtonClicked(ActionEvent event) throws IOException {
		System.out.println("Login Button Clicked!");
		
		 if(isAllFieldFillup()){
	            String userName = tfusername.getText().trim();
	            String password = pfpassword.getText();
	            
	            try {
					if (isValidCredentials(userName,password)){						
						
						 Parent person = FXMLLoader.load(getClass().getResource("PersonOverview.fxml"));
                         Scene personScene = new Scene(person);
                         Stage personStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
                         personStage.hide();
                         personStage.setScene(personScene);
                         personStage.setTitle("Person Overview");
                         personStage.show();									
						
						System.out.println("Login Successfully!");
					}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	        }
	}	
	
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
		
	
    private boolean isValidCredentials(String userName, String password) throws SQLException {
        boolean userPassOk = false;

        DBConnection database = new DBConnection();
        Connection connection = database.getConnection();
        Statement statement = connection.createStatement();
        String str = "select * from admin where username = '"+userName+"' and dbAdminPassword = '"+password+"';";
        
        System.out.println(str);
        ResultSet resultSet = statement.executeQuery(str);

        while (resultSet.next()){
            if(resultSet.getString("username")!=null && resultSet.getString("dbAdminPassword")!=null){
                userPassOk = true;
            }
        }

        if(!userPassOk) {
            NotificationType notificationType = NotificationType.ERROR;
            TrayNotification tray = new TrayNotification();
            tray.setTitle("Wrong Information");
            tray.setMessage("Incorrect username or password");
            tray.setNotificationType(notificationType);
            tray.showAndDismiss(Duration.millis(3000));

            tfusername.clear();
            pfpassword.clear();

            userPassOk = false;
        }
        return userPassOk;
    }    
    
    private boolean isAllFieldFillup(){
        boolean fillup;
        if(tfusername.getText().trim().isEmpty()||pfpassword.getText().isEmpty()){
            NotificationType notificationType = NotificationType.INFORMATION;
            TrayNotification tray = new TrayNotification();
            tray.setTitle("Attention!!!");
            tray.setMessage("Username or Password should not Empty.");
            tray.setNotificationType(notificationType);
            tray.showAndDismiss(Duration.millis(3000));
            fillup = false;
        }
        else fillup = true;
        return fillup;
    }		
}
